server:
  address: "server:12345"
loop:
  amount: 500
  period: "150ms"
log:
  level: "INFO"
batch:
  maxAmount: 10
bet:
  firstName: "Lionel Andres" 
  lastName: "Messi"
  document: 33016244
  birthDate: "1987-06-24"
  number: 10