name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    networks: ['testing_net']
    volumes: ['./server/config.ini:/config/config.ini']

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    networks: ['testing_net']
    depends_on: ['server']
    volumes: ['./client/config.yaml:/config/config.yaml', './.data/agency-1.csv:/bets.csv']
    environment: {'CLI_ID': '1', 'CLI_FIRST_NAME': 'Juan C.', 'CLI_LAST_NAME': 'Lopez', 'CLI_DOCUMENT': '30904465', 'CLI_BIRTH_DATE': '1999-03-17', 'CLI_NUMBER': '4'}

  server-checker:
    container_name: server-checker
    image: busybox
    networks: ['testing_net']
    command: tail -f /dev/null

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
