name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    networks: ['testing_net']
    volumes: ['./server/config.ini:/config/config.ini']

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    networks: ['testing_net']
    depends_on: ['server']
    volumes: ['./client/config.yaml:/config/config.yaml']
    environment: {'CLI_ID': '1', 'NOMBRE': 'Juan C.', 'APELLIDO': 'Lopez', 'DOCUMENTO': '30904465', 'NACIMIENTO': '1999-03-17', 'NUMERO': '4'}

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    networks: ['testing_net']
    depends_on: ['server']
    volumes: ['./client/config.yaml:/config/config.yaml']
    environment: {'CLI_ID': '2', 'NOMBRE': 'Mark V.', 'APELLIDO': 'Grayson', 'DOCUMENTO': '23000000', 'NACIMIENTO': '1967-12-12', 'NUMERO': '8'}

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    networks: ['testing_net']
    depends_on: ['server']
    volumes: ['./client/config.yaml:/config/config.yaml']
    environment: {'CLI_ID': '3', 'NOMBRE': 'Carlo Antonio', 'APELLIDO': 'Piastri', 'DOCUMENTO': '23000001', 'NACIMIENTO': '2000-01-01', 'NUMERO': '15'}

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    networks: ['testing_net']
    depends_on: ['server']
    volumes: ['./client/config.yaml:/config/config.yaml']
    environment: {'CLI_ID': '4', 'NOMBRE': 'Toshinori', 'APELLIDO': 'Yagi', 'DOCUMENTO': '23000002', 'NACIMIENTO': '2014-04-02', 'NUMERO': '16'}

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
